#### URGEL, HANNAH PAULEEN A. URGEL - 2ECE-B

# NORMALIZATION PROBLEM: 

Normalization is one of the most basic preprocessing techniques in data analytics. This involves centering and scaling process. Centering means subtracting the data from the mean and scaling means dividing with its standard deviation. Mathematically, normalization can be expressed as:

𝑍 = 𝑋 − 𝑥̅ / 𝜎

In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and .std() calls.

In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized ndarray as X_normalized.npy


In [1]:
import numpy as np

In [5]:
X = np.random.rand(5, 5)

In [6]:
print("Original Array X:\n", X)

Original Array X:
 [[0.98353468 0.38621188 0.96092985 0.11611052 0.85833245]
 [0.47790702 0.11344014 0.48899677 0.31309082 0.06690041]
 [0.23222636 0.36462738 0.32758009 0.69890747 0.81788496]
 [0.79839662 0.00994932 0.09407366 0.89312836 0.7419494 ]
 [0.3469048  0.85017109 0.01570894 0.1050119  0.74636124]]


In [10]:
mean = X.mean()
std = X.std()

In [11]:
print("Mean:", mean)

Mean: 0.47233344512637837


In [12]:
print("Standard Deviation:", std)

Standard Deviation: 0.3257685273905709


In [15]:
X_normalized = (X - mean) / std

In [16]:
print("\nNormalized Array\n:", X_normalized)


Normalized Array
: [[ 1.56921616 -0.2643643   1.49982691 -1.09348479  1.18488734]
 [ 0.01710901 -1.10168194  0.05115081 -0.48882138 -1.2445433 ]
 [-0.73704813 -0.33062145 -0.44434419  0.69550619  1.06072712]
 [ 1.00090447 -1.41936403 -1.16113053  1.29169909  0.82763045]
 [-0.38502382  1.1598347  -1.40168391 -1.12755382  0.84117334]]


In [17]:
np.save("X_normalized.npy", X_normalized)

# DIVISIBLE BY 3 PROBLEM:

Create the following 10 x 10 ndarray

In [18]:
import numpy as np

In [19]:
A = np.arange(1, 101) ** 2
A = A.reshape(10, 10)

In [20]:
print("Array A (10x10 with squares of first 100 integers):\n", A)

Array A (10x10 with squares of first 100 integers):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [21]:
div_by_3 = A[A % 3 == 0]

In [22]:
print("\nElements divisible by 3:\n", div_by_3)


Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [23]:
np.save("div_by_3.npy", div_by_3)